### ISSUE TITLE
The indexer for XX Network is stuck

### ISSUE THREAD

**Issue by stepanLav** [xx-labs/xxstats#28]
Looks like the Indexer for https://xx.polkastats.io/  is stuck

https://xx.polkastats.io/extrinsics/

<img width="200" alt="Screenshot 2022-11-25 at 15 21 21" src="https://user-images.githubusercontent.com/40560660/203962268-61919a46-183b-4e16-89de-6c82d5b88c2e.png">

https://xxscan.io/extrinsics

<img width="200" alt="Screenshot 2022-11-25 at 15 22 14" src="https://user-images.githubusercontent.com/40560660/203962336-6d7212bd-4f80-453c-85bc-a562b63cdc67.png">

**Comment by mariopino** [comment]
Thanks for reporting @stepanLav , this was fixed.
